name: Run script

on:
  schedule:
    # * is a wildcard that matches any value
    # 30 23 * * * means every day at 23:30
    - cron:  '30 23 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}

    steps:
    - name: Write Google Credentials
      run: echo "$GOOGLE_CREDENTIALS" > key.json

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run script
      run: python main.py